name: Do Rename & Deploy

on:
  workflow_call:
    inputs:
      pom-path:
        description: 'Path to the pom.xml file'
        required: true
        type: string
#  push:
#    branches:
#      - master
#  workflow_dispatch:

env:
  MAVEN_ARGS: "-s ./.m2/settings.xml -B -f ${{ inputs.pom-path }}"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository -Dmaven.artifact.threads=10"
  JAVA_VERSION: "17"

jobs:
  build:
    name: Maven build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          java-package: jdk

      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.9

#      - name: Set up NodeJS
#        uses: actions/setup-node@v4
#        with:
#          node-version: 'lts/hydrogen'
#
#      - name: Set up Angular
#        run: |
#          npm install -g @angular/cli@15

      - name: Configure Maven settings
        run: |
          mkdir -p ./.m2
          cp .github/maven/settings.xml ./.m2/settings.xml

      - name: "DEBUG : Validate tools"
        run: |
          java -version
          javac -version
          mvn -v
#          npm -v
#          ng version
          export BRANCH_NAME=$(echo ${{ github.ref_name }} | sed 's,.*/,,g')
          export CURRENT_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          export NEW_VERSION=$(echo $CURRENT_VERSION | sed --regexp-extended "s/([0-9.]*)-(SNAPSHOT|RELEASE|release)/\1-$BRANCH_NAME-\2/")
          echo '>>>>>>>>>>>>>>>>>>>>>'
          echo REF_NAME           ${{ github.ref_name }}
          echo BRANCH_NAME        $BRANCH_NAME
          echo CURRENT_VERSION    $CURRENT_VERSION
          echo NEW_VERSION        $NEW_VERSION
          echo '<<<<<<<<<<<<<<<<<<<<<'

      - name: Test vars persistence
        run : |
          echo NEW_VERSION        $NEW_VERSION

      - name: Build with Maven
        env:
          REPO_HOSTNAME: ${{ secrets.REPO_HOSTNAME }}
          REPO_SPECIAL_SAUCE: ${{ secrets.REPO_SPECIAL_SAUCE }}
          REPO_USERNAME: ${{ secrets.REPO_USERNAME }}
          REPO_PASSWORD: ${{ secrets.REPO_PASSWORD }}
        run: mvn clean deploy
