name: Do Rename & Deploy

on:
  workflow_call:
    inputs:
      pom-path:
        description: 'Path to the pom.xml file'
        required: true
        type: string
      require-angular:
        description: 'Add angular to the runner'
        required: false
        default: false
        type: boolean
      do-rename:
        description: 'Rename for branch/tag'
        required: false
        default: false
        type: boolean
      do-sonarqube:
        description: 'Do SonarQube scan'
        required: false
        default: false
        type: boolean
      do-owasp:
        description: 'Perform OWASP check'
        required: false
        default: false
        type: boolean
#  push:
#    branches:
#      - master
#  workflow_dispatch:

env:
  MAVEN_ARGS: "-s ./.m2/settings.xml -B -f ${{ inputs.pom-path }}"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository -Dmaven.artifact.threads=10"
  JAVA_VERSION: "17"
  REPO_HOSTNAME: ${{ secrets.REPO_HOSTNAME }}
  REPO_SPECIAL_SAUCE: ${{ secrets.REPO_SPECIAL_SAUCE }}
  REPO_USERNAME: ${{ secrets.REPO_USERNAME }}
  REPO_PASSWORD: ${{ secrets.REPO_PASSWORD }}

jobs:
  build:
    name: Maven build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          java-package: jdk

      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.9

      - name: Get Maven Settings
        uses: actions/checkout@v4
        with:
          repository: wtg-bolero/DevOps_CI-Workflows
          path: alex_maven
          ref: master
#          token: ${{ secrets.GH_PAT }} # `GH_PAT` is a secret that contains your PAT
          sparse-checkout: |
            .github/maven/settings.xml
          sparse-checkout-cone-mode: false
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Validate tooling - java
        run: |
          java -version
          javac -version
          mvn -v

      - name: Set up NodeJS
        if: ${{ inputs.require-angular }}
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/hydrogen'

      - name: Set up Angular
        if: ${{ inputs.require-angular }}
        run: |
          npm install -g @angular/cli@15

      - name: Validate tooling - angular
        if: ${{ inputs.require-angular }}
        run: |
          npm -v
          ng version

      - name: Do Maven version change
        if: ${{ inputs.do-rename }}
        run: |
          export BRANCH_NAME=$(echo ${{ github.ref_name }} | sed 's,.*/,,g')
          export CURRENT_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          export NEW_VERSION=$(echo $CURRENT_VERSION | sed --regexp-extended "s/([0-9.]*)-(SNAPSHOT|RELEASE|release)/\1-$BRANCH_NAME-\2/")
          echo '>>>>>>>>>>>>>>>>>>>>>'
          echo REF_NAME           ${{ github.ref_name }}
          echo BRANCH_NAME        $BRANCH_NAME
          echo CURRENT_VERSION    $CURRENT_VERSION
          echo NEW_VERSION        $NEW_VERSION
          echo '<<<<<<<<<<<<<<<<<<<<<'
          mvn clean versions:set -DnewVersion=$NEW_VERSION

      - name: Do OWASP scan
        if: ${{ inputs.do-owasp }}
        run: |
          mvn -DnvdApiKey=${{ secrets.NVD_API_KEY }} org.owasp:dependency-check-maven:aggregate

      - name: Do Maven build and deploy
        run: |
          mvn clean deploy
